# Generated by Django 3.2 on 2021-05-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namelastname', models.CharField(max_length=100, verbose_name='Name and Lastname')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('total_view', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Amount')),
                ('billing_status', models.BooleanField(default=False, verbose_name='Paid')),
                ('itemname', models.CharField(max_length=50, null=True, verbose_name='Item name')),
                ('say', models.IntegerField(blank=True, default=0, null=True, verbose_name='How much')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
