# Generated by Django 3.2 on 2021-05-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_added',
        ),
    ]
