# Generated by Django 3.2 on 2021-05-23 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210508_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
