# Generated by Django 3.2 on 2021-05-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_field',
            new_name='date',
        ),
    ]
